### ISSUE TITLE
我是小白，为什么用Gantt_FJSP()函数画FJSP的结果图报错？

### ISSUE THREAD

**Issue by SuYuuuuuu** [Aihong-Sun/FJSP_FP_GA#4]
Traceback (most recent call last):
  File "D:/PythonProject/FJSP_FP_GA-main/Algorithm/FJSP/GA_for_FJSP.py", line 217, in <module>
    Gantt_FJSP(Best_JS)
  File "D:\PythonProject\FJSP_FP_GA-main\Gantt.py", line 42, in Gantt_FJSP
    plt.barh(i , width=ET[j]-ST[j],
  File "C:\Software\Anaconda3\envs\Pytorch\lib\site-packages\matplotlib\pyplot.py", line 2457, in barh
    return gca().barh(
  File "C:\Software\Anaconda3\envs\Pytorch\lib\site-packages\matplotlib\axes\_axes.py", line 2649, in barh
    patches = self.bar(x=left, height=height, width=width, bottom=y,
  File "C:\Software\Anaconda3\envs\Pytorch\lib\site-packages\matplotlib\__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Software\Anaconda3\envs\Pytorch\lib\site-packages\matplotlib\axes\_axes.py", line 2441, in bar
    color = itertools.chain(itertools.cycle(mcolors.to_rgba_array(color)),
  File "C:\Software\Anaconda3\envs\Pytorch\lib\site-packages\matplotlib\colors.py", line 473, in to_rgba_array
    if len(c) == 0:
TypeError: object of type 'int' has no len()

**Comment by SuYuuuuuu** [comment]
谢谢，问题已解决！
